robot_base_frame: base_footprint
transform_tolerance: 0.5
update_frequency: 3.0
publish_frequency: 3.0
obstacle_range: 5.0
raytrace_range: 3.0
always_send_full_costmap: false
footprint: [[-0.175, -0.2], [-0.175, 0.2], [0.175, 0.2], [0.175, -0.2]]
inflation_radius: 1.75
cost_scaling_factor: 2.58
